spring.application.name=SAFe-Com API

# Database connection (Postgres) - set via environment or edit here
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:SAFe-Com}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Aumenta o limite do tamanho do JSON que o Spring aceita (padrão é pequeno)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-post-size=10MB